import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Devs Closet</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Navbar />
            <div>
                <Image
                    className='contain'
                    src='https://source.unsplash.com/random/1920x1080/?coding,development'
                    layout='responsive'
                    width='100%'
                    height='30'
                    alt='hero'
                    priority
                />
            </div>

            <Footer />
        </div>
    );
}
